server:
  port: 10006

spring:
  application:
    name: member-service-nacos-provider #名称，可以自己指定
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/e_commerce_center_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置 Nacos 地址
#暴露所有监控点
management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  mapperLocations: classpath:mapper/*.xml #后面 mapper 文件的位置
  type-aliases-package: com.feng.springcloud.entity # 实体类的包路径
